test error on warning for github actions 3

diff --git a/.github/workflows/melpazoid.yml b/.github/workflows/melpazoid.yml
--- a/.github/workflows/melpazoid.yml
+++ b/.github/workflows/melpazoid.yml
@@ -31,4 +31,14 @@ jobs:
           RECIPE: (russian-calendar :fetcher github :repo "Anoncheg1/emacs-russian-calendar")
           # set this to false (or remove it) if the package isn't on MELPA:
           # EXIST_OK: false
-        run: echo $GITHUB_REF && make -C ~/melpazoid |& grep -q "Warning" && exit 1
+        run: |
+          echo $GITHUB_REF
+          if make -C ~/melpazoid |& tee output.log; then
+            if grep -q "Warning" output.log; then
+              echo "Warnings detected, failing workflow"
+              exit 1
+            fi
+          else
+            echo "Make command failed, failing workflow"
+            exit 1
+          fi
